import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BodySingle from "components/layouts/body/single/body-single";
import { getComics } from "dh-marvel/services/marvel/marvel.service";
import { Comic } from "interface/types";
import ComicGrid from "dh-marvel/components/ui/ComicGrid/ComicGrid";
import ComicPagination from "dh-marvel/components/ui/Pagination/ComicPagination";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

interface Props {
  comics: Comic[];
  total: number;
}

const Index: NextPage<Props> = ({ comics, total }) => {
  const PER_PAGE = 12;
  const [page, setPage] = useState(1);
  const router = useRouter()

  const handleChange = (pageNum: number) => {
    setPage(pageNum);
  };

  useEffect(() => {
    router.query.page = String(page)
    router.push(router)
  }, [page]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle title={"Comics"}>
        <ComicPagination
          page={page}
          total={Math.ceil(total / PER_PAGE)}
          setPage={handleChange}
        />
        <ComicGrid comics={comics} />
        <ComicPagination
          page={page}
          total={Math.ceil(total / PER_PAGE)}
          setPage={handleChange}
        />
      </BodySingle>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async({query}) => {
  const PER_PAGE = 12;
  const page = Number(query?.page) || 1
  
  const { data } = await getComics((page-1)*PER_PAGE,PER_PAGE);

  return {
    props: {
      comics: data.results,
      total: data.total,
    },
  };
}

export default Index;
